### ISSUE TITLE
Check powinien przechodzić bez błędów

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/cr17#2]
Aby można było zgłosić pakiet na CRAN `check()` powinien przechodzić bez błędów.
Aby sprawdzić z czym są problemy napisz
```
library(devtools)
check()
```
będąc w katalogu z pakietem

**Comment by MagdaMlynarczyk** [comment]
check przechodzi bez błędów.
jeden warning, jaka licencja?

**Comment by MagdaMlynarczyk** [comment]
wpisałam GPL, tak jak u Agi
