### ISSUE TITLE
Argumenty crSummary

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/cr17#6]
Teraz funkcja crSummary spodziewa się nazw zmiennych
przyjętym sposobem przekazywania zmiennej cenzurowanej jest też przez funkcję Surv
np. tak:
```
crSummary(Surv(time, event) ~ gender, LUAD)
```

Dodawaj też nazwy argumentów do przykładów, łatwiej będzie zrozumieć co się dzieje w przykładowych wywołaniach
```
crSummary("time", "event", "gender", LUAD, 1200, "alive")
```

**Comment by MagdaMlynarczyk** [comment]
to nie zadziała w przypadku tej funkcji. Kolumna 'event' będzie miała tyle poziomów, co liczba ryzyk + 1 (cenzorowanie). A funkcja crSummary wykonuje 2 różne podejścia. Kolumnę 'event' do przypadku analizy przeżycia muszę zmodyfikować na dwupoziomową, więc nie mogę od razu pracować na wyniku funkcji Surv. 

Co więcej, w moim podejściu 'event' nie musi być numeryczny jak w przypadku funkcji Surv. Co ma swoje plusy, np. na wykresach mamy nazwy ryzyk a nie kodowanie.

W całym pakiecie jest też używana taka notacja, czy na pewno trzeba ją zmieniać?
